// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt5VSTNN9BDo7fU0e7ZUWFCIs4Lzg3dhg',
    appId: '1:820390279795:web:937b31333afda908048806',
    messagingSenderId: '820390279795',
    projectId: 'instagram-clone-3e606',
    authDomain: 'instagram-clone-3e606.firebaseapp.com',
    storageBucket: 'instagram-clone-3e606.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlhMh1961aDEYY59Di5CboL_divKoYmFs',
    appId: '1:820390279795:android:96570ea88d8b49b3048806',
    messagingSenderId: '820390279795',
    projectId: 'instagram-clone-3e606',
    storageBucket: 'instagram-clone-3e606.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFgc1gdDRm-s3dgFnMXPtM2eMM-0VV0VA',
    appId: '1:820390279795:ios:e6c3e89c16a02ffc048806',
    messagingSenderId: '820390279795',
    projectId: 'instagram-clone-3e606',
    storageBucket: 'instagram-clone-3e606.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFgc1gdDRm-s3dgFnMXPtM2eMM-0VV0VA',
    appId: '1:820390279795:ios:e6c3e89c16a02ffc048806',
    messagingSenderId: '820390279795',
    projectId: 'instagram-clone-3e606',
    storageBucket: 'instagram-clone-3e606.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt5VSTNN9BDo7fU0e7ZUWFCIs4Lzg3dhg',
    appId: '1:820390279795:web:b4a392b5396a4bd7048806',
    messagingSenderId: '820390279795',
    projectId: 'instagram-clone-3e606',
    authDomain: 'instagram-clone-3e606.firebaseapp.com',
    storageBucket: 'instagram-clone-3e606.appspot.com',
  );
}
